### ISSUE TITLE
Optional Requirements for Components

### ISSUE THREAD

**Issue by tmarkmann** [DavidPL1/Hyperion#41]
Add the possibility of optional requirements for components. A component should be able to depend on component a or component b. If one of them is already started, the 'requires' constraint should be satisfied.

**Comment by DavidPL1** [comment]
Instead of the OR based approach I introduced a new configuration field for a component that holds a list of optional requirements. Components providing those will be listed as dependency of said component and if no component at all provides a specified optional requirement, the requirement is ignored.

This allows to model a consistent hierarchy of dependencies, that does not break, if some components in between may be excluded by a specific system file. 

If this is what you intended please close the issue
